export const ICON_NAMES = {
    LOGO: {
        HYDRA_ICON:"HYDRA_ICON",
        HYDRA_TEXT:"HYDRA_TEXT",
    },
    COMMUNICATION: {
        PHONE_ICON:"PHONE_ICON",
        MESSAGE_ICON:"MESSAGE_ICON",
        GLOCATION_ICON:"GLOCATION_ICON"
    },
    ASSETS:{
        ARROW_RIGHT_ICON: "ARROW_RIGHT_ICON",
        ARROW_RIGHT_LONG_ICON:"ARROW_RIGHT_LONG_ICON",
        ARROW_DOWN_ICON:"ARROW_DOWN_ICON",
        MENU_ICON:"MENU_ICON",
        PREV_ICON:"PREV_ICON",
        NEXT_ICON:"NEXT_ICON",
    },
    VECTOR:{
        VECTOR_1_ICON:"VECTOR_1_ICON",
        VECTOR_2_ICON:"VECTOR_2_ICON",
        VECTOR_3_ICON:"VECTOR_3_ICON",
        VECTOR_15_ICON:"VECTOR_15_ICON",
        VECTOR_21_ICON:"VECTOR_21_ICON",
    },
    SITE:{
        FB_ICON:"FB_ICON",
        YOUTUBE_ICON:"YOUTUBE_ICON",
        INSTAGRAM_ICON:"INSTAGRAM_ICON",
        LINKEDIN_ICON:"LINKEDIN_ICON",
        TWITTER_ICON:"TWITTER_ICON",
        PRINTEREST_ICON:"PRINTEREST_ICON"

    }
  };